Add Rails 7.2 support
GSA-TTS/rails-template pull request #113
Opened 2024-08-21 18:29 UTC by rahearn

Changes:

* Generate rails 7.2 apps.
* general gem version updates
* add a dependabot config to the github actions generator
* small fix to `bin/trestle` and `bin/auditree` to pass CLI args into docker

closes #109

2024-08-22 14:19 UTC, rahearn commented
Converting to draft as the `update` command needs more work.

2024-08-22 14:25 UTC, beechnut requested changes
I ran it, I have a project, and I ran `rails c` and `rails s` with the expected results.

However, the end of the log exited with a non-zero exit code? Not sure what's going on there.

```sh
# ... log log log ...
create mode 100644 zap.conf
         run  git add . from "."
         run  git commit -a -m 'Initial commit' from "."
On branch main
nothing to commit, working tree clean
⚠️   1   # <-- the non-zero exit
```

Otherwise, just left a couple suggested changes for the readme.

2024-08-22 14:25 UTC, beechnut commented on README.md
change (non-blocking): Even though I think I was the person who wrote the readme, I was confused trying to follow it! The commands are nested inside numbers, then bullets, then sub-bullets, then parentheses. I 

change: It asked me about docker-trestle and compliance-as-code and I had no idea what to select and the readme doesn't explain it. Could you add something about that to guide a decision?

2024-08-22 14:43 UTC, rahearn commented
> However, the end of the log exited with a non-zero exit code? Not sure what's going on there.

I'm 99% certain that's from the `git commit` resulting in "nothing to commit, working tree clean". Which is itself surprising, unless you ran it multiple times with the same destination directory?

2024-08-22 14:48 UTC, beechnut commented
Just to double-check that, I ran `git status` in a repo with nothing to commit and a clean working tree and got

```
→  git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
🆗 # <-- this is my terminal's version of a 0 exit code
```

2024-08-22 16:19 UTC, rahearn commented on README.md
> +$ rails_template_18f new <project name> --hotwire ADDITIONAL_CONFIG_OPTIONS
I don't love `ADDITIONAL_CONFIG_OPTIONS` but couldn't think of a better way to say "insert any --no-skip... options here"

2024-08-27 18:12 UTC, pauldoomgov approved these changes
Thanks for addressing the feedback! Approved!

2024-08-27 18:13 UTC, merged